parse_config:
  layer_legend_map:
    Symbols: "Sym"
    Numbers: "Num"
    System: "Sys"

  raw_binding_map:
    "&none":
      tap: ""
      type: none

    "&caps_word": $$mdi:file-word-box$$

    "&trans": $$mdi:triangle-down-outline$$

  zmk_keycode_map:
    # Symbols
    GRAVE: "`"
    TILDE: "~"
    EXCL: "!"
    AT: "@"
    HASH: "#"
    DLLR: $
    PRCNT: "%"
    CARET: ^
    AMPS: "&"
    STAR: "*"
    LPAR: (
    RPAR: )
    MINUS: "-"
    UNDER: _
    EQUAL: "="
    PLUS: "+"
    LBKT: "["
    LBRC: "{"
    RBKT: "]"
    RBRC: "}"
    BSLH: '\'
    PIPE: "|"
    SEMI: ";"
    SQT: "'"
    DQT: '"'
    COMMA: ","
    DOT: "."
    FSLH: "/"

    # Other
    PSCRN: $$mdi:monitor-screenshot$$

    # Language
    LANG_1: $$mdi:syllabary-hangul$$

    # Navigation
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    PG_UP: $$mdi:chevron-double-up$$
    PG_DN: $$mdi:chevron-double-down$$
    HOME: $$mdi:page-first$$
    END: $$mdi:page-last$$

    # Whitespace
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    SPACE: $$mdi:keyboard-space$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LMETA: $$mdi:penguin$$
    
    # Media
    C_PP: $$mdi:play-pause$$
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$

    # Volume
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$

    # Bluetooth
    BT_NXT: $$mdi:chevron-left$$ $$mdi:bluetooth$$
    BT_PRV: $$mdi:bluetooth$$ $$mdi:chevron-right$$
    BT_CLR: $$mdi:bluetooth-off$$

draw_config:
  append_colon_to_layer_header: false
  separate_combo_diagrams: true
  combo_diagrams_scale: 2
